Финальное задание 9
Almor47/java-filmorate pull request #2
Opened 2023-03-22 04:07 UTC by Almor47

2023-03-23 17:16 UTC, VertigoMaker requested changes
Отметил дополнения

2023-03-23 17:16 UTC, VertigoMaker commented on src/main/java/ru/yandex/practicum/filmorate/conroller/FilmController.java
> +            throw new ValidationException("Ошибка валидации");
Всегда лучше писать причины ошибки! В данном примере можно отыгарть от checkValidateFilm и в нём кидать ошибку, ловя её на этом уровне, либо же возвращая (bool, string) где string - ошибка, и писать её (так обычно делают в случае наличия глобальной обработки ошибок)

2023-03-23 17:16 UTC, VertigoMaker commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String email;
Рекомендую проставить аннотации в полях классов - NotBlank, Length, все они помогут упростить валидацию и помочь читающему с первого взгляда понять что требуется от класса.
Конкретно для email есть Email, избавляющий от головной боли с форматом.

2023-03-23 17:43 UTC, Almor47 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String email;
А как тесты писать на классы с аннотациями? Там же функциональные не подойдут

2023-03-24 13:48 UTC, VertigoMaker approved these changes
Всё верно!

2023-03-25 05:44 UTC, merged