Финальное задание
Almor47/java-filmorate pull request #4
Opened 2023-05-04 17:52 UTC by Almor47

2023-05-04 22:52 UTC, EvgenyKoptubenko commented on HELP.md
> +* [Building REST services with Spring](https://spring.io/guides/tutorials/rest/)
Похоже этот файл со стандартной документацией Спринга. В качестве документации проекта не подходит. Предлагаю или переписать на документацию проекта или удалить

2023-05-04 22:52 UTC, EvgenyKoptubenko commented
В файле README.md должна быть ссылка на файл диаграммы.

2023-05-04 22:56 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql = "select * from FILMS f JOIN FILMS_RATING fr ON f.MPA_ID = fr.MPA_ID where FILM_ID = ?";
Когда достается фильм почему-то не достается его жанр. попробуй сделать это одним запросом

2023-05-04 22:59 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/MpaDbStorage.java
> +import org.springframework.jdbc.core.JdbcTemplate;
Точно ли эта зависимость подключается через pom?

2023-05-04 23:02 UTC, EvgenyKoptubenko commented
По-моему, для сущностей должен быть сделать полный crud. Сейчас невозможно удалить пользователя

2023-05-04 23:02 UTC, EvgenyKoptubenko commented
Если отправить такой запрос, то падает c NullPointerException
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"FilmName",
	"email":"email@email.com",
  "login":"login",
	"birthday":"2001-01-01",
	"duration":22
}'

java.lang.NullPointerException: null
	at ru.yandex.practicum.filmorate.annotation.ReleaseDateConstraintValidator.isValid(ReleaseDateConstraintValidator.java:10) ~[classes/:na]
	at ru.yandex.practicum.filmorate.annotation.ReleaseDateConstraintValidator.isValid(ReleaseDateConstraintValidator.java:7)

2023-05-04 23:04 UTC, EvgenyKoptubenko commented
Если отправить такой запрос
curl --request PUT \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"email":"wrong_emai@lmail.com",
  "login":"login22",
	"birthday":"2012-04-23T18:25:43.511Z"
}'

То сообщение об ошибке приходит со странным описанием

2023-05-04 23:06 UTC, EvgenyKoptubenko commented
Если отправить такой запрос несколько раз, то приходит 500-я ошибка
curl --request PUT \
  --url http://localhost:8080/users/1/friends/3 \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"email":"email3@email.com"
}'

{
	"timestamp": "2023-05-04T23:05:24.431+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/users/1/friends/3"
}


insert into FRIENDSHIP(USER_ID,FRIEND_ID) values (?,?) [23505-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_B ON PUBLIC.FRIENDSHIP(USER_ID, FRIEND_ID) VALUES ( /* key:1 */ 1, 3)"; SQL statement:
insert into FRIENDSHIP(USER_ID,FRIEND_ID) values (?,?) [23505-214]] with root cause

org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_B ON PUBLIC.FRIENDSHIP(USER_ID, FRIEND_ID) VALUES ( /* key:1 */ 1, 3)"; SQL statement:
insert into FRIENDSHIP(USER_ID,FRIEND_ID) values (?,?) [23505-214]

Должен быть тогда Conflict, а не 500-я ошибка

2023-05-04 23:09 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sql2 = "select * from FILM_GENRE fg JOIN GENRE g ON g.GENRE_ID = fg.GENRE_ID where FILM_ID = ?";
попробуй сделать так, чтобы фильм и жанр вытаскивались из базы данных одним запросом

2023-05-04 23:10 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть предложения по улучшению кода

2023-05-06 07:25 UTC, Almor47 commented on HELP.md
> +* [Building REST services with Spring](https://spring.io/guides/tutorials/rest/)
Если отправить такой запрос, то падает c NullPointerException
curl --request POST
--url http://localhost:8080/films
--header 'Content-Type: application/json'
--header 'X-Sharer-User-Id: 12231'
--data '{
"name":"FilmName",
"email":"[email@email.com](mailto:email@email.com)",
"login":"login",
"birthday":"2001-01-01",
"duration":22
}'

java.lang.NullPointerException: null
at ru.yandex.practicum.filmorate.annotation.ReleaseDateConstraintValidator.isValid(ReleaseDateConstraintValidator.java:10) ~[classes/:na]
at ru.yandex.practicum.filmorate.annotation.ReleaseDateConstraintValidator.isValid(ReleaseDateConstraintValidator.java:7)
тут наверное какое-то ошибка? ведь у фильма нет таких полей? birthday и email к фильму не относится

2023-05-07 01:27 UTC, EvgenyKoptubenko commented on HELP.md
> +* [Building REST services with Spring](https://spring.io/guides/tutorials/rest/)
Так значит Bad Request, а не NullPointerException

2023-05-07 01:27 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-05-07 06:38 UTC, merged